### ISSUE TITLE
On node.js PLS parser fails

### ISSUE THREAD

**Issue by oxfn** [nickdesaulniers/javascript-playlist-parser#13]
String objects in Node.js does not provide `.trim()` method. See error message:
```
C:\Var\Music\_Radio\soma.fm\node_modules\playlist-parser\lib\parser.min.js:32
)(\d+)=(.+)\r?/i,b=function(b){var c,d,e,f,g,h,i,j,k,l;for(g=[],l=b.trim().spl
                                                                    ^
TypeError: Object [playlist]
numberofentries=3
File1=http://uwstream2.somafm.com:7770
Title1=SomaFM: Seven Inch Soul (#1 128k mp3): Vintage soul tracks from the original 45 RPM vinyl.
Length1=-1
File2=http://uwstream3.somafm.com:7770
Title2=SomaFM: Seven Inch Soul (#2 128k mp3): Vintage soul tracks from the original 45 RPM vinyl.
Length2=-1
File3=http://ice.somafm.com/7soul
Title3=SomaFM: Seven Inch Soul (Firewall-friendly 128k mp3) Vintage soul tracks from the original 45 RPM vinyl.
Length3=-1
Version=2
 has no method 'trim'
    at Object.b [as parse] (C:\Var\Music\_Radio\soma.fm\node_modules\playlist-parser\lib\parser.min.js:32:1437)
    at Object.<anonymous> (C:\Var\Music\_Radio\soma.fm\merge.js:12:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by nickdesaulniers** [comment]
What version of node are you running?

```
➜  temp  node -v
v0.12.0
➜  temp  node
> String.prototype.trim
[Function: trim]
```

**Comment by oxfn** [comment]
Sorry, my fault. This is not an issue. I was trying to pass buffer object into parse instead of string.
